/**
 * GPM API
 * Group Project Manager
 *
 * OpenAPI spec version: v1
 * Contact: vincenzorizzomy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GroupGoals { 
    readonly id?: number;
    complete?: boolean;
    group: number;
    goal: number;
}