/**
 * GPM API
 * Group Project Manager
 *
 * OpenAPI spec version: v1
 * Contact: vincenzorizzomy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User { 
    readonly id?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    matricola: string;
    group?: number;
    /**
     * Designates whether the user can log into this admin site.
     */
    readonly isStaff?: boolean;
    /**
     * Designates that this user has all permissions without explicitly assigning them.
     */
    readonly isSuperuser?: boolean;
}