/**
 * GPM API
 * Group Project Manager
 *
 * OpenAPI spec version: v1
 * Contact: vincenzorizzomy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserRegister { 
    username: string;
    email: string;
    password1: string;
    password2: string;
    firstName: string;
    lastName: string;
    matricola: string;
}